app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/howzatdb
    username: postgres
    password: password
    pool-size: 30

  jwt:
    secret-key: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    token-prefix: "Bearer "
    token-expiration-after-days: 10