CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE players (
    player_uuid uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	role VARCHAR(50),
	matches INT,
	runs INT,
	strike_rate DECIMAL(5,2),
	highest INT,
	highest_not_out BOOLEAN,
	wickets INT,
	economy DECIMAL(4,2),
	best_spell_wickets INT,
	best_spell_runs INT
);

--sample data
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Kelsy', 'Cristofolo', 'all-rounder', 51, 1448, 207.53, 142, true, 47, 14.86, 3, 85);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Selle', 'Tarbert', 'keeper', 10, 2463, 41.07, 146, false, 40, 11.13, 3, 84);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Boycey', 'Neill', 'all-rounder', 97, 2094, 97.29, 140, false, 45, 12.03, 4, 39);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Heath', 'Mark', 'keeper', 6, 1557, 5.87, 141, false, 47, 5.24, 3, 57);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Shantee', 'Wingrove', 'bastsman', 72, 2300, 207.58, 17, false, 44, 4.72, 6, 31);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Carrissa', 'Anger', 'all-rounder', 17, 2376, 235.0, 10, false, 2, 7.41, 0, 35);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Ignazio', 'DelaField', 'keeper', 64, 2466, 218.51, 18, false, 10, 2.06, 3, 17);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Livvie', 'Newsham', 'keeper', 55, 1414, 54.43, 150, false, 39, 13.55, 7, 61);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Reagan', 'Godlee', 'all-rounder', 43, 2232, 117.66, 126, false, 19, 4.58, 5, 90);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Nataniel', 'Reboul', 'all-rounder', 25, 2053, 194.99, 145, true, 70, 19.99, 1, 76);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Aubine', 'Splain', 'keeper', 55, 2223, 222.73, 130, true, 6, 18.8, 9, 27);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Barthel', 'Steeples', 'all-rounder', 5, 2265, 85.1, 87, true, 58, 10.44, 7, 73);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Alexio', 'Van der Mark', 'keeper', 46, 2078, 100.54, 19, false, 15, 19.87, 0, 24);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Emmye', 'Croley', 'keeper', 69, 2447, 155.65, 138, false, 45, 7.53, 6, 39);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Rasia', 'Whelpton', 'all-rounder', 73, 593, 249.78, 87, true, 35, 7.58, 8, 83);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Ravid', 'Persich', 'all-rounder', 69, 2046, 80.06, 15, true, 3, 5.11, 1, 37);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Dredi', 'Briton', 'keeper', 40, 1875, 224.66, 114, false, 69, 3.3, 10, 95);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Jennee', 'Oganesian', 'bastsman', 93, 814, 236.01, 46, true, 3, 10.72, 5, 91);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Shandie', 'Taffurelli', 'all-rounder', 38, 1940, 95.14, 52, false, 11, 18.85, 2, 74);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Diann', 'Libbis', 'all-rounder', 37, 1457, 220.65, 53, true, 54, 12.47, 5, 58);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Amelita', 'Arnet', 'all-rounder', 26, 691, 99.42, 27, true, 23, 19.18, 0, 80);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('De', 'Euels', 'bolwer', 70, 2486, 55.55, 138, false, 9, 5.75, 8, 92);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Gracie', 'Hobden', 'all-rounder', 28, 703, 19.56, 74, false, 14, 15.47, 10, 47);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Fredelia', 'Torald', 'all-rounder', 20, 257, 117.39, 16, false, 50, 19.92, 4, 87);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Davine', 'Loxton', 'bolwer', 34, 2239, 91.04, 95, true, 1, 12.83, 0, 31);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Petra', 'Matthius', 'all-rounder', 9, 47, 206.71, 140, false, 64, 2.13, 1, 63);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Benedikt', 'Hazeldine', 'keeper', 23, 185, 206.85, 143, false, 5, 13.37, 9, 10);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Janaya', 'Rainey', 'all-rounder', 58, 2493, 67.56, 131, true, 21, 16.76, 2, 20);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Hyatt', 'D''Ambrosi', 'bastsman', 72, 2051, 193.46, 2, false, 26, 13.13, 3, 12);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Wells', 'Telford', 'all-rounder', 24, 1233, 19.99, 127, true, 48, 18.16, 1, 71);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Sheila', 'Lodwick', 'bolwer', 74, 1944, 224.65, 64, false, 3, 19.01, 8, 37);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Adeline', 'Marrett', 'keeper', 94, 1582, 133.47, 8, true, 36, 8.34, 3, 95);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Rogers', 'Hort', 'bolwer', 8, 245, 184.97, 142, true, 48, 16.33, 3, 13);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Mercy', 'Roebuck', 'all-rounder', 95, 1197, 102.69, 48, true, 55, 19.84, 0, 46);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Nickolas', 'Messitt', 'keeper', 20, 613, 222.75, 77, false, 17, 3.5, 8, 70);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Bo', 'Woodberry', 'bastsman', 58, 1068, 6.52, 78, true, 13, 2.18, 1, 34);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Orv', 'Marklin', 'bastsman', 21, 1989, 202.59, 43, true, 15, 11.29, 3, 92);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Adelle', 'Shotboulte', 'keeper', 45, 1172, 201.52, 12, false, 28, 18.65, 8, 32);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Ilysa', 'Dincke', 'bolwer', 32, 472, 29.74, 12, true, 0, 11.45, 3, 81);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Riva', 'Bester', 'keeper', 43, 804, 52.02, 76, false, 13, 6.44, 9, 65);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Birch', 'Wolton', 'bastsman', 10, 731, 54.99, 60, false, 17, 11.16, 7, 69);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Annmaria', 'Mewrcik', 'bastsman', 79, 356, 112.36, 6, true, 63, 4.49, 5, 45);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Silvano', 'Muscat', 'bastsman', 99, 2007, 146.42, 9, false, 17, 11.92, 1, 2);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Zaccaria', 'Mongain', 'all-rounder', 9, 49, 48.44, 124, false, 45, 7.87, 2, 20);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Janela', 'Deinert', 'keeper', 40, 751, 61.19, 50, true, 55, 9.53, 6, 49);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Alric', 'Braidford', 'bastsman', 18, 1882, 86.79, 150, true, 48, 14.91, 8, 73);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Clare', 'Kohnert', 'all-rounder', 22, 819, 38.95, 21, false, 27, 9.62, 9, 55);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Rickie', 'Clawe', 'all-rounder', 6, 397, 136.43, 65, true, 59, 10.92, 5, 30);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Marylou', 'Rudiger', 'all-rounder', 31, 2063, 108.85, 91, false, 39, 18.93, 10, 6);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Fabian', 'Loade', 'all-rounder', 5, 2247, 48.03, 21, true, 58, 8.05, 4, 28);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Greggory', 'Tussaine', 'bolwer', 38, 300, 169.06, 25, false, 49, 16.52, 6, 44);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Cornie', 'Dossett', 'all-rounder', 0, 118, 129.09, 143, true, 54, 10.57, 6, 78);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Dell', 'Bedward', 'all-rounder', 58, 2043, 89.68, 3, false, 27, 8.19, 9, 80);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Clemmy', 'Giabucci', 'all-rounder', 8, 2457, 55.86, 28, false, 39, 11.59, 9, 23);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Teri', 'Garner', 'all-rounder', 52, 1030, 103.63, 131, true, 58, 2.84, 3, 31);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Walsh', 'Frankom', 'all-rounder', 22, 1811, 121.77, 72, true, 12, 4.06, 9, 55);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Olly', 'Edmeades', 'keeper', 99, 836, 240.04, 146, false, 34, 3.43, 8, 56);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Toma', 'Imbrey', 'all-rounder', 70, 177, 174.53, 43, true, 59, 11.28, 6, 20);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Zared', 'Flemmich', 'keeper', 0, 1971, 54.53, 111, true, 17, 10.1, 6, 8);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Town', 'Keilty', 'keeper', 61, 217, 185.77, 109, false, 69, 11.11, 6, 35);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Lyndsay', 'Woakes', 'all-rounder', 74, 485, 161.5, 10, true, 6, 9.21, 3, 14);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Hortense', 'Orteau', 'all-rounder', 30, 420, 27.54, 15, false, 69, 15.47, 7, 24);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Jemimah', 'Maunders', 'all-rounder', 93, 2092, 120.18, 29, true, 29, 5.66, 7, 63);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Germayne', 'Roles', 'all-rounder', 94, 2081, 67.93, 58, false, 59, 2.9, 6, 18);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Jeth', 'Zecchii', 'all-rounder', 100, 154, 0.41, 144, false, 19, 5.35, 4, 82);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Blinnie', 'Riha', 'all-rounder', 43, 1649, 63.34, 113, false, 19, 1.22, 1, 37);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Jenine', 'Domnin', 'all-rounder', 33, 982, 183.43, 31, false, 31, 4.27, 4, 49);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Alessandra', 'Van der Son', 'all-rounder', 49, 1235, 187.24, 132, false, 34, 15.33, 4, 87);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Elna', 'Pollastrino', 'keeper', 26, 1748, 178.06, 144, true, 33, 15.13, 1, 52);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Harley', 'Pegden', 'all-rounder', 43, 2382, 77.01, 122, true, 24, 17.53, 1, 75);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Ruperta', 'McGilbon', 'all-rounder', 43, 1091, 193.52, 88, false, 44, 11.45, 0, 52);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Frayda', 'Swann', 'bastsman', 66, 729, 122.39, 148, true, 41, 9.79, 6, 49);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Rowen', 'Treanor', 'keeper', 17, 1774, 219.91, 129, true, 32, 9.59, 0, 16);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Janek', 'Miquelet', 'keeper', 57, 1238, 137.44, 147, false, 26, 14.03, 4, 69);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Dareen', 'Shurrock', 'bolwer', 42, 1060, 96.04, 115, false, 38, 2.87, 3, 83);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Alvira', 'Beyn', 'bastsman', 74, 1841, 213.66, 12, false, 68, 5.1, 10, 12);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Jenny', 'Barabich', 'all-rounder', 45, 1267, 136.52, 69, false, 3, 3.83, 9, 68);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Dorene', 'Binden', 'all-rounder', 37, 184, 245.81, 77, true, 54, 5.0, 3, 54);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Jasmine', 'MacQueen', 'all-rounder', 81, 1748, 171.43, 114, true, 41, 18.09, 6, 77);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Tybalt', 'Ramas', 'keeper', 98, 501, 217.75, 87, true, 13, 4.26, 0, 79);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Gordon', 'Sudlow', 'keeper', 76, 2001, 38.64, 45, false, 60, 18.03, 3, 20);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Benson', 'Matteini', 'keeper', 20, 965, 237.04, 128, false, 17, 12.68, 7, 81);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Wilona', 'Klosterman', 'keeper', 0, 588, 188.91, 51, false, 32, 11.28, 7, 92);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Giorgi', 'Panton', 'all-rounder', 74, 1144, 214.75, 38, false, 65, 9.2, 3, 28);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Rosie', 'Matteo', 'bastsman', 95, 91, 99.33, 12, true, 6, 7.74, 9, 0);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Tarah', 'Santo', 'all-rounder', 88, 1200, 152.63, 8, true, 48, 15.92, 10, 42);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Casey', 'Midgley', 'keeper', 95, 2005, 78.34, 94, true, 70, 3.13, 2, 29);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Hurley', 'Musslewhite', 'all-rounder', 96, 1646, 99.29, 123, false, 22, 14.5, 1, 83);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Willi', 'Lamyman', 'all-rounder', 44, 1189, 193.43, 104, true, 16, 8.47, 7, 40);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Catlaina', 'Crowne', 'keeper', 47, 2441, 26.28, 133, true, 58, 11.39, 2, 33);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Rafaelia', 'Lisciandri', 'bastsman', 49, 979, 244.23, 60, true, 65, 19.41, 2, 13);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Gene', 'Brister', 'all-rounder', 14, 327, 155.67, 55, true, 45, 18.01, 9, 75);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Andromache', 'Towle', 'all-rounder', 74, 930, 35.49, 94, true, 52, 7.19, 3, 2);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Kimberlyn', 'Edes', 'all-rounder', 73, 1592, 76.97, 25, false, 59, 5.14, 1, 84);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Derrik', 'Searjeant', 'all-rounder', 35, 646, 242.88, 103, false, 43, 9.76, 9, 29);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Milena', 'Hammerstone', 'bolwer', 75, 1574, 2.64, 113, true, 61, 10.43, 3, 77);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Idalina', 'Loach', 'all-rounder', 69, 1796, 74.05, 86, false, 26, 6.44, 2, 85);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Wye', 'Magauran', 'keeper', 8, 1157, 48.89, 5, false, 37, 8.85, 1, 68);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Lesly', 'Crutcher', 'bastsman', 0, 1603, 24.41, 66, true, 56, 18.9, 3, 38);
INSERT INTO players (first_name, last_name, role, matches, runs, strike_rate, highest, highest_not_out, wickets, economy, best_spell_wickets, best_spell_runs) VALUES ('Florentia', 'Milksop', 'bolwer', 34, 2324, 83.64, 53, true, 41, 3.15, 9, 98);
